### PR TITLE
fix scroll event

### PR DESCRIPTION
**Pull request by matveyvarg**
Binding of scroll event through jQuery doesn't work if body, html height is 100%. Added it through addEventListener().

### CODE REVIEW

**Comment by Amphiluke** [comment]
Hi,

Could you please provide a minimal example to reproduce the bug?

**Comment by matveyvarg** [comment]
Hi, sorry forlate reply, sure I'll provide it a little bit later.

15 сент. 2017 г. 11:07 PM пользователь "Amphiluke" <notifications@github.com>
написал:

**Comment by matveyvarg** [comment]
Just try it with html, body set to 100%.  As I read, it causes because of jQuery. jQuery cant properly handles scroll event. There is my case: 
1. Original code 
for pullreq
2. Code with my fix
for pullreq2
for pullreq3

**Comment by Amphiluke** [comment]
> Just try it with html, body set to 100%.

This is exactly what I tried first, but I didn't see any issue. Here is a live demo with `html` & `body` height set to 100%: https://jsfiddle.net/pxtx16k7/

That's why I asked for a minimum example revealing the bug. Will you please make a small fiddle so that I could see the bug for myself?

**Comment by Amphiluke** [comment]
I'm closing this PR for no activity. Unfortunately, it's not quite clear what exactly do these changes fix, as we don't have any live demo reproducing the bug. One more thing making the proposed implementation unacceptable in its current state is that the newly added event handlers are not removed by the method `destroyAPI`, and thus they result in potential memory leaks.

Feel free to report an issue or open a new PR once you are ready to provide more detailed info on any bug you found. But please read carefully the [contributing guidelines](https://github.com/Amphiluke/floating-scroll/blob/master/CONTRIBUTING.md#contributing-to-floating-scroll) first, so we could work on your issue/PR more effectively.

**Pull request closed without merging**
